# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:


- task: UseDotNet@2
  displayName: Install .Net 6 SDK
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore nuget packages
  inputs:
    command: 'restore'
    projects: '**/TodoAPI.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build web app
  inputs:
    command: 'build'
    projects: '**/TodoAPI.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: intialize entity framework
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'

- task: DotNetCoreCLI@2
  displayName: Create migration
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: 'database update --project=TodoAPI/TodoAPI.csproj'

- task: DotNetCoreCLI@2
  displayName: Run Unit Test
  inputs:
    command: 'test'
    projects: '**/*Test*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Craete web package (.zip)
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish artifact (webapp.zip)
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
